name: Build & Push to ECR

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-southeast-1
  ECR_BACKEND: 940278683083.dkr.ecr.ap-southeast-1.amazonaws.com/ilovetng-backend
  ECR_FRONTEND: 940278683083.dkr.ecr.ap-southeast-1.amazonaws.com/ilovetng-frontend

jobs:
  build-and-push:
    name: Build & Push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::940278683083:role/ilovetng-service-account-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ci/docker/backend/Dockerfile
          push: true
          tags: |
            ${{ env.ECR_BACKEND }}:latest
            ${{ env.ECR_BACKEND }}:${{ github.sha }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ci/docker/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.ECR_FRONTEND }}:latest
            ${{ env.ECR_FRONTEND }}:${{ github.sha }}
